# # build environment
# FROM node:alpine AS build
# WORKDIR /app
# COPY . .
# RUN yarn
# RUN yarn build:docker-dev

# # production environment
# FROM nginx:stable-alpine
# COPY --from=build /app/dist /usr/share/nginx/html
# COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

FROM node:20-alpine 
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .

EXPOSE 5173

CMD ["yarn", "dev"]
